image: rust:bullseye

variables:
  LLVM_SYS_170_FFI_WORKAROUND: "YES"

before_script:
  - apt-get update -qq && apt-get install -qq -y lsb-release software-properties-common
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - ./llvm.sh 17
  - apt-get install libpolly-17-dev

test:
  script:
    - cargo build
    - cargo test
    - cargo run --example nop-function
    - cargo run --example jit-function
    - echo "Hello, world!" | cargo run --example disassembler
